// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// accelerated_rpcholesky
List accelerated_rpcholesky(const arma::mat& A, int k, SEXP b_in, double stoptol, bool verbose);
RcppExport SEXP _rpcholesky_accelerated_rpcholesky(SEXP ASEXP, SEXP kSEXP, SEXP b_inSEXP, SEXP stoptolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_in(b_inSEXP);
    Rcpp::traits::input_parameter< double >::type stoptol(stoptolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(accelerated_rpcholesky(A, k, b_in, stoptol, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rpcholesky_accelerated_rpcholesky", (DL_FUNC) &_rpcholesky_accelerated_rpcholesky, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rpcholesky(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
