# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rejection_cholesky <- function(H) {
    .Call(`_rpcholesky_rejection_cholesky`, H)
}

accelerated_rpcholesky <- function(A, k, b_in, stoptol, verbose) {
    .Call(`_rpcholesky_accelerated_rpcholesky`, A, k, b_in, stoptol, verbose)
}

